---
### AWS CloudFormation template for the EC2 101 lab from the
### acloud.guru AWS Certified Develper Associate course 
AWSTemplateFormatVersion: 2010-09-09
Description: acloud.guru EC2-S3 Lab
Outputs:
  instanceId:
    Description: Instance Identifier
    Export:
      Name: 'ec2-s3:InstanceId'
    Value: !Ref ec2s3Lab
  instancePublicDNS:
    Description: Instance Public DNS
    Export:
      Name: 'ec2-s3:PublicDNS'
    Value: !GetAtt ec2s3Lab.PublicDnsName
  instancePublicIp:
    Description: Instance Public Ip
    Export:
      Name: 'ec2-s3:PublicIp'
    Value: !GetAtt ec2s3Lab.PublicIp
  securityGroupId:
    Description: Security Group Id
    Export:
      Name: 'ec2-s3:SecurityGroupId'
    Value: !GetAtt ec2s3DMZ.GroupId
Parameters:      # Default values for template parameters are useful when testing templates in the AWS Web Console
  externalCidr:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 68.5.90.175/28 # default value is intentially incorrect
  imageId:
    Description: choose a valid ami for the instance type being deployed in your region
    Type: AWS::EC2::Image::Id
    Default: ami-04681a1dbd79675a5 # may not be correct 
  instanceName:
    ConstraintDescription: must be a unique instance name.
    Description: Name of the EC2 instance
    Type: String
    Default: acg-ec2-s3-instance
  instanceType:
    Type: String
    Default: t2.micro
  keyName:
    Description: >-
      Name of an existing EC2 KeyPair in this region to enable SSH access to
      Linux instance and/or decrypt Windows password
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: acg-ec2-s3-us-east-1
  vpcId:
    Description: The id of the VPC to deploy into
    Type: AWS::EC2::VPC::Id
    Default: vpc-f3d7158a # intentionaly incorrect
  aZ:
    Description: The availability zone hosting the instance
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a # may not be correct
Resources:
  instProf:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref s3Admin
  s3Admin:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: /
      Policies: 
        - 
          PolicyName: "s3Admin"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - 
                Effect: "Allow"
                Action: "s3:*"
                Resource: "*"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"      
  ec2s3Lab:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          packages:
            yum:
              httpd: []
          files:
            /var/www/html/index.html:
              content: >-
                <html><body><h1>Hello Cloud Gurus</h1><h2>from instance
                A</h2></body></html>
              group: apache
              mode: '000644'
              owner: apache
          services:
            sysvinit:
              httpd:
                enabled: 'true'
                ensureRunning: 'true'
      Comment: Install web server
      'AWS::CloudFormation::Designer':
        id: 8873b445-5bb1-4f66-91bc-df54f140ec28
    Properties:
      IamInstanceProfile: !Ref instProf
      AvailabilityZone: !Ref aZ
      ImageId: !Ref imageId
      InstanceType: !Ref instanceType
      KeyName: !Ref keyName
      SecurityGroupIds:
        - !Ref ec2s3DMZ
      Tags:
        - Key: Name
          Value: !Join 
            - ''
            - - !Ref instanceName
        - Key: Lab
          Value: acloud.guru.ec2-s3
      UserData:
        'Fn::Base64': !Sub >
          #!/bin/bash -xe

          echo start userdata

          /opt/aws/bin/cfn-init -v --stack \${AWS::StackName} --resource
          ec2s3Lab --region \${AWS::Region}

          yum update -y

          echo end userdata
    DependsOn:
      - s3Admin
  ec2s3DMZ:
    Properties:
      GroupDescription: >-
        This SG allows traffic from the current external ip on port 80 and port
        22
      GroupName: ec2s3DMZ
      SecurityGroupIngress:
        - CidrIp: !Ref externalCidr
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
      VpcId: !Ref vpcId
      Tags:
        - Key: Name
          Value: ec2-s3WebDMZ
        - Key: Lab
          Value: acloud.guru.ec2-s3
    Type: 'AWS::EC2::SecurityGroup'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: be134cc2-eab8-4548-90bc-0d896775aa52
Metadata:
  'AWS::CloudFormation::Designer':
    be134cc2-eab8-4548-90bc-0d896775aa52:
      size:
        width: 60
        height: 60
      position:
        x: 550
        'y': 230
      z: 1
      embeds: []
    e6b4e522-d858-43da-83d6-4c50581be6f4:
      size:
        width: 60
        height: 60
      position:
        x: 450
        'y': 230
      z: 1
      embeds: []
    d5ccc0e8-11ae-4b7f-9b07-e4adbaf434e5:
      size:
        width: 60
        height: 60
      position:
        x: 350
        'y': 330
      z: 1
      embeds: []
    66881150-7307-4fc1-b216-fe13c9eb201f:
      size:
        width: 60
        height: 60
      position:
        x: 350
        'y': 230
      z: 1
      embeds: []
      isassociatedwith:
        - e6b4e522-d858-43da-83d6-4c50581be6f4
    701d91db-0636-441e-923e-ec592037ccf4:
      size:
        width: 60
        height: 60
      position:
        x: 450
        'y': 330
      z: 1
      embeds: []
      isassociatedwith:
        - d5ccc0e8-11ae-4b7f-9b07-e4adbaf434e5
    8873b445-5bb1-4f66-91bc-df54f140ec28:
      size:
        width: 60
        height: 60
      position:
        x: 550
        'y': 330
      z: 1
      embeds: []
      isassociatedwith:
        - be134cc2-eab8-4548-90bc-0d896775aa52
      dependson:
        - e6b4e522-d858-43da-83d6-4c50581be6f4
    fde45c6f-f1c0-41ad-943d-26a073b88591:
      source:
        id: 66881150-7307-4fc1-b216-fe13c9eb201f
      target:
        id: e6b4e522-d858-43da-83d6-4c50581be6f4
      z: 2
    323ca7e2-702e-423e-b5aa-691d95daf954:
      source:
        id: 8873b445-5bb1-4f66-91bc-df54f140ec28
      target:
        id: e6b4e522-d858-43da-83d6-4c50581be6f4
      z: 3

# MIT License

# Copyright (c) 2018 John Michael Miller

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.